### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by seanbmcnulty** [cryptarbitrage-code/deribit-position-greeks#1]
Hello, been getting this error and not sure how to fix it, noob coder obviously. Any ideas on how to solve?

Thank you

Exception in Tkinter callback
Traceback (most recent call last):
  File "...\anaconda3\lib\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "\deribit-position-greeks-main\main.py", line 374, in get_positions_click
    positions_list_btc, positions_list_eth, positions_list_sol = get_positions()
  File "\deribit-position-greeks-main\api_functions.py", line 32, in get_positions
    positions_list_BTC = response_dict["result"]
KeyError: 'result'

**Comment by seanbmcnulty** [comment]
all good has to do with settings, updated api_exchange_address to "https://www.deribit.com" from test environment and worked fine, thanks for the code!

**Comment by cryptarbitrage-code** [comment]
Hey,
Glad you got it sorted! And no worries, I'm glad you're finding it useful.

Cryptarbitrage
Twitter: https://twitter.com/cryptarbitrage
Medium:  https://cryptarbitrage.medium.com
Youtube: https://www.youtube.com/channel/UCQOYWWI94MvlSodyhBT2zqA
Deribit: http://deribit.trade
