### ISSUE TITLE
Calculate the greeks to all option instruments

### ISSUE THREAD

**Issue by 21orangehat** [cryptarbitrage-code/deribit-position-greeks#2]
Hi @cryptarbitrage-code,

Thank again you for this tool!

I'm trying to calculate the greeks to all option instruments, but as some parameters are missing, I don't know how to
manage it. Maybe you can enlighten me.

 Following the Deribit APIs, there's no endpoint with all data necessary.

For example, I expected to have all data necessary to calculate the greeks using the get_instruments endpoint, but
we don't have the underlying_price and mark_iv on it.

Then, I'm using the get_book_summary_by_currency, but we don't have mark_iv

I don't know if there's a way to calculate and find the mark_iv with that data, but if yes, would be nice.

Of course, there's the ticker endpoint that have all greeks calculated, but I don't want to get all instruments first
and then get one by one ticker.

Can you help me with that?

**Comment by cryptarbitrage-code** [comment]
Well if you only want to use the data in get_book_summary_by_currency, you do have the mark_price and underlying_price. Along with the strike price and time left until expiry, which can be inferred from the instrument name with some calculations, you can then calculate the mark_iv using some Black Scholes formulas.
